CREATE TABLE IF NOT EXISTS categories (
id SERIAL NOT NULL,
name CHARACTER VARYING(25) NOT NULL,
description CHARACTER VARYING(70) NOT NULL DEFAULT '',

PRIMARY KEY(id),
UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS producers (
id SERIAL NOT NULL,
name CHARACTER VARYING(40) NOT NULL,
postal_code CHARACTER VARYING(15) NOT NULL,
country CHARACTER VARYING(30) NOT NULL,
region CHARACTER VARYING(30) NOT NULL,
locality CHARACTER VARYING(40) NOT NULL,
street CHARACTER VARYING(50) DEFAULT '',
building CHARACTER VARYING(25) DEFAULT '',

PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS goods (
id SERIAL NOT NULL,
name CHARACTER VARYING(30) NOT NULL,
sort CHARACTER VARYING(30) NOT NULL,
description CHARACTER VARYING(900) NOT NULL DEFAULT '',
category_id INT NOT NULL,
producer_id INT NOT NULL,

PRIMARY KEY(id),
UNIQUE(name, sort, category_id, producer_id),

CONSTRAINT fk_category
FOREIGN KEY (category_id)
REFERENCES categories (id)
ON DELETE NO ACTION ON UPDATE NO ACTION,

CONSTRAINT fk_producer
FOREIGN KEY (producer_id)
REFERENCES producers (id)
ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS storehouse(
id SERIAL NOT NULL,
good_id INTEGER NOT NULL,
ttn_num VARCHAR(15),
date TIMESTAMPTZ NOT NULL DEFAULT now(),
unit CHARACTER VARYING(2) DEFAULT 'кг',
quantity NUMERIC(9, 3) NOT NULL,
price NUMERIC(11, 2) NOT NULL,

PRIMARY KEY(id),

UNIQUE(good_id),

CONSTRAINT fk_good
FOREIGN KEY (good_id)
REFERENCES goods (id)
ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS roles(
id SERIAL NOT NULL,
name CHARACTER VARYING(20) NOT NULL,

PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS users(
id SERIAL NOT NULL,
name CHARACTER VARYING(30) NOT NULL,
password CHARACTER VARYING(68) NOT NULL,
email CHARACTER VARYING(30) NOT NULL,
enabled BOOLEAN NOT NULL DEFAULT TRUE,

PRIMARY KEY(id),

UNIQUE(email)
);

CREATE TABLE IF NOT EXISTS users_roles(
user_id INTEGER NOT NULL,
role_id INTEGER NOT NULL,

PRIMARY KEY(user_id, role_id),

CONSTRAINT fk_user
FOREIGN KEY (user_id)
REFERENCES users (id)
ON DELETE NO ACTION ON UPDATE NO ACTION,

CONSTRAINT fk_role
FOREIGN KEY (role_id)
REFERENCES roles (id)
ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS purchases(
id SERIAL NOT NULL,
user_id INTEGER NOT NULL,
storehouse_id INTEGER NOT NULL,
date TIMESTAMPTZ NOT NULL DEFAULT now(),
unit CHARACTER VARYING(2) NOT NULL DEFAULT 'кг',
quantity NUMERIC(9, 3) NOT NULL,
price NUMERIC(11, 2) NOT NULL,
status CHARACTER VARYING(8) NOT NULL DEFAULT 'reserved',

PRIMARY KEY(id),

CONSTRAINT fk_user
FOREIGN KEY (user_id)
REFERENCES users (id)
ON DELETE NO ACTION ON UPDATE NO ACTION,

CONSTRAINT fk_storehouse
FOREIGN KEY (storehouse_id)
REFERENCES storehouse (id)
ON DELETE NO ACTION ON UPDATE NO ACTION
);