version: "3.7"

services:
  db-storage:
    image: postgres:14.5
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=storage